-- Scope: MC / OWNER=MC; SQL Navigator 5.5.4.847; Oracle version unknown
-- Grain: One current product x coefficient group
-- Fan-out: Components aggregated before stored join; validate code and DU uniqueness before interpreting.
-- Proves: DQ-COEF-003 rozdiel recompute
-- Does not prove: Diagnostic aggregate, not a corrected writer. Prefix 3 is executable heuristic, not taxonomy. O.POCET may include norm loss; no extra loss multiplication. Current INT_KOD and DU uniqueness must be checked. Unsupported DU7 stays NULL. No historical eligibility or pure packed-weight claim.
-- Evidence: PM-06C, PM-07A, PM-07B
WITH component_mapping AS (
 SELECT sk.ID AS KOD_ID,sc.ID AS COMPONENT_KOD_ID,l.RID AS BOM_RID,o.POCET,
 sc.HMOTNOST_NETTO,du.DU_7,du.DU_8,du.DU_9,
 CASE WHEN du.DU_7 IS NULL THEN 0
      WHEN TRIM(TRANSLATE(TRIM(du.DU_7),'0123456789.',' ')) IS NULL
       AND LENGTH(TRIM(du.DU_7))-LENGTH(REPLACE(TRIM(du.DU_7),'.',''))<=1
      THEN TO_NUMBER(TRIM(du.DU_7),'999999999D999999999','NLS_NUMERIC_CHARACTERS=''.,''') END AS RECYCLED_PCT
 FROM MC.VYR_KUSOVNIKY_L l JOIN MC.VYR_KUSOVNIKY_O o ON o.RID_O=l.RID
 JOIN MC.VYR_KATALOG vl ON vl.ID=l.ID_VYR
 JOIN MC.VYR_KATALOG vo ON vo.ID=o.ID_VYR
 JOIN MC.SKLAD_KARTA sk ON sk.INT_KOD=vl.INT_KOD
 JOIN MC.SKLAD_KARTA sc ON sc.INT_KOD=vo.INT_KOD
 JOIN MC.CIS_DU_O du ON du.RID=sc.RID
 WHERE l.S_STAMP='0' AND o.S_STAMP='0' AND SUBSTR(vl.INT_KOD,1,1)='3'
 AND (du.DU_8 IS NOT NULL OR du.DU_9 IS NOT NULL)
), contributions AS (
 SELECT c.*,1 AS TOKEN_POSITION,'VIRGIN' AS MATERIAL_PART,
 SUBSTR(DU_8,1,INSTR(DU_8||';',';')-1) AS NK_ID,
 (100-RECYCLED_PCT)/100*HMOTNOST_NETTO*POCET AS EXPECTED_PART FROM component_mapping c
 UNION ALL
 SELECT c.*,1,'RECYCLED',SUBSTR(DU_9,1,INSTR(DU_9||';',';')-1),
 RECYCLED_PCT/100*HMOTNOST_NETTO*POCET FROM component_mapping c
 UNION ALL
 SELECT c.*,2,'VIRGIN',
 CASE WHEN INSTR(DU_8,';')>0 THEN SUBSTR(DU_8,INSTR(DU_8,';')+1,
 INSTR(DU_8||';',';',1,2)-INSTR(DU_8,';')-1) END,
 (100-RECYCLED_PCT)/100*HMOTNOST_NETTO*POCET FROM component_mapping c
 UNION ALL
 SELECT c.*,2,'RECYCLED',
 CASE WHEN INSTR(DU_9,';')>0 THEN SUBSTR(DU_9,INSTR(DU_9,';')+1,
 INSTR(DU_9||';',';',1,2)-INSTR(DU_9,';')-1) END,
 RECYCLED_PCT/100*HMOTNOST_NETTO*POCET FROM component_mapping c
), expected AS (
 SELECT KOD_ID,NK_ID,COUNT(*) AS CONTRIBUTION_ROWS,
 COUNT(DISTINCT COMPONENT_KOD_ID) AS COMPONENT_COUNT,
 SUM(CASE WHEN EXPECTED_PART IS NULL THEN 1 ELSE 0 END) AS NULL_INPUT_ROWS,
 SUM(EXPECTED_PART) AS EXPECTED_MNOZSTVO
 FROM contributions WHERE NK_ID IS NOT NULL GROUP BY KOD_ID,NK_ID
), stored AS (
 SELECT KOD_ID,NK_ID,COUNT(*) AS STORED_ROWS,SUM(MNOZSTVO) AS STORED_MNOZSTVO
 FROM MC.SK_NAKL_POLOZKY WHERE S_STAMP='0' AND POZN LIKE 'Import z kusovníka;%'
 GROUP BY KOD_ID,NK_ID
), audit AS (
 SELECT NVL(e.KOD_ID,s.KOD_ID) AS KOD_ID,NVL(e.NK_ID,s.NK_ID) AS NK_ID,
 e.CONTRIBUTION_ROWS,e.COMPONENT_COUNT,e.NULL_INPUT_ROWS,e.EXPECTED_MNOZSTVO,
 s.STORED_ROWS,s.STORED_MNOZSTVO,
 CASE WHEN e.KOD_ID IS NULL THEN 'STALE_AUTO_ROW'
      WHEN e.NULL_INPUT_ROWS>0 THEN 'MISSING_OR_UNSUPPORTED_INPUT'
      WHEN s.KOD_ID IS NULL THEN 'MISSING_STORED'
      WHEN e.COMPONENT_COUNT>1 THEN 'MULTI_COMPONENT_SAME_COEF'
      WHEN ABS(e.EXPECTED_MNOZSTVO-s.STORED_MNOZSTVO)>:tolerance THEN 'MISMATCH'
      ELSE 'MATCH' END AS AUDIT_STATUS
 FROM expected e FULL OUTER JOIN stored s ON s.KOD_ID=e.KOD_ID AND s.NK_ID=e.NK_ID
)
SELECT * FROM audit WHERE NULL_INPUT_ROWS=0 AND STORED_ROWS IS NOT NULL AND ABS(EXPECTED_MNOZSTVO-STORED_MNOZSTVO)>:tolerance;
